/*
→ TOPIC - if else  
*/

// 1. to compare two numbers and print the greater number

#include<iostream>
using namespace std ;

int main()
{
    int n1 , n2 ;
    cout<<"\nenter two nums ";
    cin>>n1>>n2 ;
    if(n1>n2)
      cout<<"\nn1 is greater than n2 "  ;
    if(n2>n1)
      cout<<"\nn2 is greater than n1 "  ;
    if(n1==n2)
      cout<<"\nboth numbers are equal "  ;

    return 0;

}


/*
                                 ASSIGNMENTS 

2. enter mrp of book , give 10% discount if mrp > 1000 otherwise give 5% discount  after discount print net price 

3. enter sale price and cost price of book print profit or loss

                      SOLUTIONS ON " IFELSEASSIGNSOL.CPP "
                      
*/