
→ AIM - programs like 
→ 1. addition 
→ 2. subtraction 
→ 3. multiplication 
→ 4. division 
by taking input from users 

#include<iostream>
using namespace std;

int main()
{
    int n1 , n2 , addition , subtraction , multiplication , division  ;
    
    cout<<"\n enter first number = " ;
    cin>>n1 ;

    cout<<"\n enter second number = " ;
    cin>>n2 ;

    addition = n1 + n2 ;
    cout<<"\n addition of n1 and n2 is = "  << addition ;

    subtraction = n1 - n2 ;
    cout<<"\n subtraction of n1 and n2 is = "  << subtraction ;

    multiplication = n1 * n2 ;
    cout<<"\n multiplication of n1 and n2 is = "  << multiplication ;

    division = n1 / n2 ;
    cout<<"\n division of n1 and n2 is = "  << division ;
    
    return 0;
}

→ ASSIGNMENTS

 → 1 .enter principle , rate and time print simple interest
 HINT -  Simple Interest Formula
           si=p*r*t/100
 → 2. enter marks of 5 subjects and print sum and percentage
 → 3. enter mrp of book give 10% dis and print net price
 HINT -  Discount Calculation Example:
         dis=mrp*10/100
         net=mrp-dis
 → 4. enter 2 nos and print their value after interchange (using temp variable)
 → 5. enter 2 nos and print their value after swap(without using temp)













