/*
→ TOPIC - loop
→ DEFINATION - A loop is a programming construct that repeats a block of code as long as a specified condition is true.
               It allows for efficient iteration over data structures or repeated execution of code without having to write it multiple times.
*/

#include <iostream>
using namespace std;

int main()
{
    for (int i = 1; i <= 5; i++)
    {
        cout << "\nhello user";
    }

    return 0;
}

// ASSIGNMENTS ( DO ALL THESE WITH THE HELP OF LOOP ) 

// 1. to print hello user 5 times along with serial wise numbering 
// 2. to print counting from 1 to 10  
// 3. to print nums like 2 4 6 8 10
// 4. to print nums like 1 2 4 8 16 32 64 128 2
// 5. to print nums like 1 4 9 16 25 36 49 64 81 100
// 6. to print sum of all nums upto 10 like 1+2+3+4+5+6+7+8+9+10
// 7. to print product of all nums upto 10 like 1*2*3*4*5*6*7*8*9*10