
→ AIM - programs like 
        1. addition 
        2. subtraction 
        3. multiplication 
        4. division

#include<iostream>
using namespace std;

int main()
{
    int n1 = 10 , n2 = 15 , addition , subtraction , multiplication , division  ;
    
    addition = n1 + n2 ;
    cout<<"\n addition of n1 and n2 is = "  << addition ;

    subtraction = n1 - n2 ;
    cout<<"\n subtraction of n1 and n2 is = "  << subtraction ;

    multiplication = n1 * n2 ;
    cout<<"\n multiplication of n1 and n2 is = "  << multiplication ;

    division = n1 / n2 ;
    cout<<"\n division of n1 and n2 is = "  << division ;
    
    return 0;
}









