/*
→ TOPIC - WHILE LOOP
*/

#include <iostream>
using namespace std;

int main()
{
    // 1. Initialization: Set the starting value
    int i = 1;

    // 2. Condition: The loop runs as long as 'i' is less than or equal to 5
    while (i <= 5)
    {
        cout << "Number: " << i << endl;

        // 3. Updation: Increase 'i' by 1 so the loop doesn't run forever
        i++;
    }

    return 0;
}

// ASSIGNMENTS

// 1. Sum of Digits     %
// 2. Reverse of Digits
// 3. Print a number to Word 123=> One Two Three
// 4. enter a number and check is it arm strong or not